name: Analyze, Build and Deploy

on: [push]

jobs:
  semantic-pull-request:
    name: "Semantic"
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/semantic_pull_request.yml@v1

  analyze:
    name: "Analyze"
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      min_coverage: 90
      flutter_channel: stable
      flutter_version: 3.3.8

  build:
    name: Build
    needs: [semantic-pull-request, analyze]
    runs-on: ubuntu-latest
    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@v3
      - name: 🐦 Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter_version: 3.3.8
      - name: 📦 Install Dependencies
        run: |
          flutter pub global activate very_good_cli
          very_good --analytics false
          very_good packages get --recursive
      - run: flutter build web -t lib/main_production.dart
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: build
          path: build/web

  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: build
          path: build/web
      - name: Deploy to firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_FLUTTER_WEB_DEPLOY_2B520 }}"
          channelId: live
          projectId: flutter-web-deploy-2b520
